---
title: "Tablero de Evaluación de Impacto"
subtitle: "Monitoreo en Tiempo Real - FAO"
format: 
  html:
    toc: true
    toc-location: left
    theme: cosmo
    code-fold: true
editor: source
---

```{r Procesamiento datos, include=FALSE}
# 0. Leer librerías.
library(pacman)
p_load("tidyverse", "plotly", "flexdashboard", "reactable", "openxlsx",
       "janitor", "stringr", "stringi")

# 1. Enlace para tener datos actualizados 'todo el tiempo'. 
url_fao_data <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vSGcdqxColk_BnF7NgrgP6hzUnkFmA-rQfPE6ptC8FsLWPYzXoqq_2TCdnTj8Cm5l2POt0Lmf9YaXwW/pub?output=xlsx"

# 2. Descarga de datos en tiempo real
df <- read.xlsx(url_fao_data) |> 
  clean_names() |>
  # Generar columnas auxiliares
  mutate(treatment = ifelse(en_los_ultimos_seis_meses_ha_tomado_las_capacitaciones_sobre_estadistica_agricola_o_pecuaria_presencial_o_virtualmente == "No, no las he tomado", 0, 1),
         modalidad = case_when(en_los_ultimos_seis_meses_ha_tomado_las_capacitaciones_sobre_estadistica_agricola_o_pecuaria_presencial_o_virtualmente == "No, no las he tomado" ~ "Sin capacitación",
                               en_los_ultimos_seis_meses_ha_tomado_las_capacitaciones_sobre_estadistica_agricola_o_pecuaria_presencial_o_virtualmente == "Sí, presencialmente" ~ "Presencialmente",
                               en_los_ultimos_seis_meses_ha_tomado_las_capacitaciones_sobre_estadistica_agricola_o_pecuaria_presencial_o_virtualmente == "Sí, virtualmente" ~ "Virtualmente",
                               en_los_ultimos_seis_meses_ha_tomado_las_capacitaciones_sobre_estadistica_agricola_o_pecuaria_presencial_o_virtualmente == "Sí, de las 2 formas" ~ "Híbrido")) 

# Identificar respuesta correcta por pregunta.
df <-  df |>
  mutate(nombre_del_cader_ddr_u_oref_donde_labora = 
           str_trim(toupper(stri_trans_general(nombre_del_cader_ddr_u_oref_donde_labora, "latin-ascii"))),
         p_1= ifelse(el_rendimiento_obtenido_se_expresa_en_kilogramos_por_hectareas=="Falso",1,0),
         p_2= ifelse(la_variable_valor_de_la_produccion_se_captura_manualmente_en_el_sistema_raw=="Falso",1,0),
         p_3= ifelse(cuando_existe_una_diferencia_notable_entre_el_precio_de_venta_reportado_directamente_por_un_productor_en_su_parcela_y_el_precio_de_ese_mismo_producto_en_la_central_de_abastos_local_cual_es_el_criterio_para_registrar_el_precio_medio_rural_pmr=="Registrar el precio del productor, ya que el PMR se refiere al precio pagado en la zona de producción (primera mano), sin incluir costos de flete o intermediación",1,0),
         p_4= ifelse(la_superficie_siniestrada_del_mes_puede_ser_mayor_a_la_superficie_sembrada=="Falso",1,0),
         p_5= ifelse(en_el_programa_agricola_se_registran_las_expectativas_de_siembra_y_cosecha_antes_del_inicio_del_ciclo_agricola=="Verdadero",1,0),
         p_6= ifelse(cual_de_las_siguientes_variables_es_formulada_automaticamente_por_el_sistema=="c) Rendimiento obtenido",1,0),
         p_7= ifelse(que_apartado_del_sistema_raw_se_utiliza_para_revisar_si_existen_capturas_pendientes=="b) Validación de Completez",1,0),
         p_8= ifelse(cual_de_los_siguientes_motivos_es_valido_para_dar_de_baja_un_cultivo=="d) Todas las anteriores",1,0),
         p_9= ifelse(quien_es_el_principal_usuario_de_la_estadistica_agricola_y_pecuaria_registrada_en_la_raw=="La propia Secretaría de Agricultura del Gobierno Federal",1,0),
         p_10= ifelse(la_superficie_sembrada_debe_ser_mayor_o_igual_que=="Superficie cosechada y siniestrada",1,0),
         p_11= ifelse(en_que_categoria_o_grupo_se_debe_clasificar_la_alfalfa_para_su_correcto_registro_en_el_sistema=="Perennes especiales",1,0),
         p_12= ifelse(el_precio_a_pie_de_granja_o_pagado_al_productor_es_el_precio_mas_barato_al_que_se_puede_comprar_un_producto=="Falso",1,0),
         p_13= ifelse(los_parametros_productivos_indican_un_maximo_y_un_minimo_y_no_puede_haber_datos_fuera_de_este_rango_bajo_ninguna_circunstancia=="Falso",1,0),
         p_14= ifelse(solo_debe_registrarse_informacion_proveniente_de_senasica_rastros_municipales_entre_otras_instituciones=="Falso",1,0),
         p_15= ifelse(el_valor_de_la_produccion_se_obtiene_multiplicando_el_volumen_por_el_precio_promedio_encontrado_en_los_mercados_locales=="Falso",1,0),
         p_16= ifelse(el_sistema_productivo_tecnificado_se_caracteriza_por_bajo_uso_de_tecnologia_y_mano_de_obra_familiar=="Falso",1,0),
         p_17= ifelse(en_que_unidades_se_registra_la_leche=="Miles de litros",1,0),
         p_18= ifelse(cual_de_los_siguientes_sistemas_productivos_es_mas_probable_que_tenga_un_mayor_rendimiento_productivo=="Especializado",1,0),
         p_19= ifelse(cual_de_las_siguientes_caracteristicas_debe_cumplir_la_carne_en_canal_de_bovino_selecciona_todas_las_opciones_que_apliquen=="Desangrado y sin piel, Abierto a lo largo de la línea media, Separado de la cabeza por el cuello, Sin vísceras, excepto los riñones; quedando el diafragma adherido",1,0),
         p_20= ifelse(cual_opcion_describe_mejor_el_ganado_en_engorda=="Animales cuya función zootécnica es la producción de carne",1,0),
         p_21= ifelse(cual_es_la_formula_correcta_para_calcular_el_volumen_total_en_pie=="(Número de cabezas x peso promedio en pie)/1000",1,0),
         p_22= ifelse(si_al_revisar_la_informacion_de_un_rastro_municipal_notas_que_el_peso_promedio_por_cabeza_de_los_bovinos_sacrificados_aumento_drasticamente_respecto_al_mes_anterior_cual_es_la_accion_de_validacion_correcta_antes_de_capturar=="Investigar con los productores o el rastro si hubo introducción de razas de mayor peso, cambios en la dieta o engorda, y justificarlo en las observaciones del sistema",1,0))

# Evaluate each question individually----
df <- df |>
  mutate(agricola = rowSums(pick(p_1:p_11), na.rm = T),
         pecuario = rowSums(pick(p_12:p_22), na.rm = T))
                                                
# Results by question and results by area----
df.resumen <- df |> 
  group_by(entidad_federativa) |>
  summarise(across(p_1:p_22, \(x) sum(x, na.rm = T)),
            mean_agri = mean(agricola, na.rm=T),
            mean_pec = mean(pecuario, na.rm=T))


## We need to add total of states to evaluate the wrong percentage----

n.states <- df |>
  group_by(entidad_federativa) |>
  count()

df.resumen <- left_join(df.resumen, n.states)

df.resumen <- df.resumen |>
  mutate(across(c(p_1:p_22), \(x) x/n, .names = "{.col}_")) 

## Graph of pecuario-agricola per state----
df.resumen.tc <- df |> 
  group_by(entidad_federativa, treatment) |>
  summarise(across(p_1:p_22, \(x) sum(x, na.rm = T)),
            mean_agri = mean(agricola, na.rm=T),
            mean_pec = mean(pecuario, na.rm=T)) |>
  select(entidad_federativa, treatment, mean_agri, mean_pec) |>
  pivot_longer(cols = c(mean_agri, mean_pec), names_to = "modulo", values_to = "promedio") 



# Mean and standar deviation of groups----
## Grouping by state
df.means.state <- df |>
  group_by(treatment, entidad_federativa, modalidad) |>
  summarise(mean=mean(score),
            sd=sd(score),
            n=n())
## Without groups
df.means <- df |>
  group_by(treatment, modalidad) |>
  summarise(mean=mean(score),
            median=median(score),
            sd=sd(score),
            n=n())

## Means by group an topic----
df.means.top <- df |> 
  group_by(treatment) |>
  summarise(across(c(agricola, pecuario), \(x) mean(x, na.rm=T)),
            across(c(agricola, pecuario), \(x) median(x, na.rm=T), .names = "{.col}_median"))

## Data frame for heat map----
df.hm <- df.resumen |> select(entidad_federativa, p_1_:p_22_) |>
  pivot_longer(cols = c(p_1_:p_22_), names_to = "pregunta", values_to = "porcentaje")
```

```{r heat map}
df.hm |>
  mutate(pregunta = factor(pregunta,levels = c("p_1_", "p_2_", "p_3_", "p_4_", "p_5_", "p_6_", "p_7_", "p_8_", "p_9_", "p_10_", "p_11_",
                                               "p_12_", "p_13_", "p_14_", "p_15_", "p_16_", "p_17_", "p_18_", "p_19_", "p_20_", "p_21_", "p_22_"))) |>
ggplot(aes(x=pregunta, y=entidad_federativa, fill= porcentaje)) + 
  geom_tile(colour = 'white')+
  scale_fill_viridis_c(name = "Porcentaje de respuestas correctas", direction = -1) +
  theme(axis.text.x = element_text(angle = 90))

```

```{r otras cosas}
# Data: mtcars:
data <- as.matrix(mtcars)

# basic heatmap
p <- plot_ly(x=colnames(data), y=rownames(data), z = data, type = "heatmap") %>%
    layout(margin = list(l=120))
p



## To hold methodological validation we need to filter states which dont follow a #random training on ddrs.
### No realistic model
#model <- lm(score ~ treatment, data=df)
#summary(model)
#
#
#model <- lm(score ~ treatment, data=filter(df,
#                                           modalidad %in% c("Presencialmente", #"Sin capacitación")))
#summary(model)
#
#
#unique(df$entidad_federativa)
### Realistic model 
#df_clean <- df |>
#  filter(entidad_federativa %in% c("Zacatecas", "Michoacán de Ocampo", "San Luis #Potosí", "Campeche", "Puebla", "Nayarit",
#                                   "Coahuila de Zaragoza", "Chihuahua", "Querétaro #de Arteaga", "Puebla", "Durango"))
#
#
#model.v <- lm(score ~ treatment, data=df_clean)
#summary(model.v)
#
#model.v <- lm(score ~ treatment, data=filter(df_clean,
#                                           modalidad %in% c("Presencialmente", #"Sin capacitación")))
#
#summary(model.v)
#
#
#df |>
#  ggplot(aes(fill = as.factor(treatment), x=score))+
#  geom_histogram(aes(y=after_stat(density)),
#                 alpha=.0,
#                 position = 'identity') +
#  geom_density(alpha = .5) +
#  geom_vline(xintercept = df.means$median[1], colour = 'blue', linewidth = 1)+
#  #geom_vline(xintercept = df.means$mean[2], colour = 'green', linewidth = 1)+
#  geom_vline(xintercept = df.means$median[3], colour = 'red', linewidth = 1)+
#  #geom_vline(xintercept = df.means$mean[4], colour = 'purple', linewidth = 1)+
#  scale_fill_manual(values=c("0"="darkblue", "1"="lightgreen"), 
#                    labels = c("No capacitados", "Capacitados"))+
#  xlab("Calificación")+ylab("")+
#  scale_x_continuous(expand = c(0,0))+
#  scale_y_continuous(expand = c(0,0))+
#  theme(plot.background = element_blank(),
#        panel.background = element_blank(),
#        axis.line = element_line(color='black'),
#        legend.title = element_blank(),
#        panel.grid = element_blank(),
#        legend.background = element_blank(),
#        legend.text = element_text(color='black', size=9))
#ggsave(here("Todos_diferencia.png"), width = 7, height = 7)
#
#
#
#
#df |>
#  ggplot(aes(fill = as.factor(treatment), x=pecuario))+
#  geom_histogram(aes(y=after_stat(density)),
#                 alpha=.0,
#                 position = 'identity') +
#  geom_density(alpha = .5) +
#  geom_vline(xintercept = df.means.top$pecuario[1], colour = 'blue', linewidth = #1)+
#  geom_vline(xintercept = df.means.top$pecuario[2], colour = 'green', linewidth = #1)+
#  scale_fill_manual(values=c("0"="darkblue", "1"="lightgreen"), 
#                    labels = c("No capacitados", "Capacitados"))+
#  xlab("Calificación")+ylab("")+
#  scale_x_continuous(expand = c(0,0))+
#  scale_y_continuous(expand = c(0,0))+
#  theme(plot.background = element_blank(),
#        panel.background = element_blank(),
#        axis.line = element_line(color='black'),
#        legend.title = element_blank(),
#        panel.grid = element_blank(),
#        legend.background = element_blank(),
#        legend.text = element_text(color='black', size=9))
#ggsave(here("Pecuario_diferencia.png"), width = 7, height = 7)
#
#
#df |>
#  ggplot(aes(fill = as.factor(treatment), x=agricola))+
#  geom_histogram(aes(y=after_stat(density)),
#                 alpha=.0,
#                 position = 'identity') +
#  geom_density(alpha = .5) +
#  geom_vline(xintercept = df.means.top$agricola[1], colour = 'blue', linewidth = #1)+
#  geom_vline(xintercept = df.means.top$agricola[2], colour = 'green', linewidth = #1)+
#  scale_fill_manual(values=c("0"="darkblue", "1"="lightgreen"), 
#                    labels = c("No capacitados", "Capacitados"))+
#  xlab("Calificación")+ylab("")+
#  scale_x_continuous(expand = c(0,0))+
#  scale_y_continuous(expand = c(0,0))+
#  theme(plot.background = element_blank(),
#        panel.background = element_blank(),
#        axis.line = element_line(color='black'),
#        legend.title = element_blank(),
#        panel.grid = element_blank(),
#        legend.background = element_blank(),
#        legend.text = element_text(color='black', size=9))
#ggsave(here("Agricola_diferencia.png"), width = 7, height = 7)
#
#
#
## The same thing but only states with random assignation
#df_clean |>
#  ggplot(aes(fill = as.factor(treatment), x=score))+
#  geom_histogram(aes(y=after_stat(density)),
#                 alpha=.0,
#                 position = 'identity') +
#  geom_density(alpha = .5) +
#  geom_vline(xintercept = df.means$mean[1], colour = 'darkblue', linewidth = 1)+
#  geom_vline(xintercept = df.means$mean[2], colour = 'lightgreen', linewidth = 1)+
#  scale_fill_manual(values=c("0"="lightgreen", "1"="darkblue"), 
#                    labels = c("No capacitados", "Capacitados"))+
#  xlab("Calificación")+ylab("")+
#  scale_x_continuous(expand = c(0,0))+
#  scale_y_continuous(expand = c(0,0))+
#  theme(plot.background = element_blank(),
#        panel.background = element_blank(),
#        axis.line = element_line(color='black'),
#        legend.title = element_blank())
#
#
#
#
#
#
## Resume per state
#respuestas.ent <- df.means.state |>
#  ungroup() |>
#  select(modalidad, entidad_federativa, n) |>
#  pivot_wider(names_from = modalidad, values_from = n) |>
#  adorn_totals(where = c("row", "col"))


```



